#!/bin/sh

### BEGIN INIT INFO
# Provides:         kano-peripherals
# Required-Start:
# Required-Stop:
# X-Start-Before:   
# Default-Start:    2
# Default-Stop:
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
    start)
	log_action_begin_msg "Clearing speaker LEDs"
	/usr/bin/kano-speakerleds off
	log_action_end_msg $?
	;;
    stop)
	;;
    restart|reload|force-reload|status)
        echo "Error: argument '$1' not supported" >&2
        exit 3
	;;
    *)
      echo "Usage: kano-peripherals [start|stop]" >&2
      exit 3
      ;;
esac

