#!/bin/bash

# libkano-hat.postinst
#
# Copyright (C) 2017 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU GPLv2
#

case "$1" in
    configure)
        # FIXME: Would love this as a proper dependency.
        #        Need to do this in the post install as
        #        otherwise can't guarantee pip
        pip install rpi_ws281x

        ;;
esac

#DEBHELPER#

exit 0
